export { default as accountVector } from  "./Accounts Vector.svg";
export { default as apple } from "./Apple.svg";
export { default as blockCardVector } from "./Block Card Vector.svg";
export { default as briefcaseVector } from "./Briefcase Vector.svg";
export { default as chipCardLogoGrey } from "./Chip Card Logo - Grey.svg";
export { default as chipCardLogoWhite } from "./Chip Card Logo - White.svg";
export { default as creditCardDecorGrey } from "./Credit Card Decor Vector - Grey.svg";
export { default as creditCardDecorWhite } from "./Credit Card Decor Vector - White.svg";
export { default as creditCardLogo } from "./Credit Card Logo.svg";
export { default as creditCardVector } from "./Credit Card Vector.svg";
export { default as creditCardVectorSelect } from "./Credit Card Vector - Select.svg";
export { default as creditCardBlue } from "./Credit Card Blue.svg";
export { default as creditCardRed } from "./Credit Card Red.svg";
export { default as creditCardYellow } from "./Credit Card Yellow.svg";
export { default as googleLogoVector } from "./Google Logo Vector.svg";
export { default as graphVector } from "./Graph Vector.svg";
export { default as headerSettingsVector } from "./Header Settings Vector.svg";
export { default as homeVector } from "./Home Vector.svg";
export { default as investmentVector } from "./Investment Vector.svg";
export { default as lifeInsuranceVector } from "./Life Insurance Vector.svg";
export { default as loansVector } from "./Loans Vector.svg";
export { default as loansVectorRed } from "./Loan Vector - Red.svg"
export { default as myPrivelegesVector } from "./My Priveleges Vector.svg";
export { default as notificationsVector } from "./Notifications Vector.svg";
export { default as padlockVector } from "./Padlock Vector.svg";
export { default as profilePicture } from "./Profile Picture.svg";
export { default as servicesVector } from "./Services Vector.svg";
export { default as servicesVectorSelect } from "./Services Vector - Select.svg";
export { default as settingsVector } from "./Settings Vector.svg";
export { default as settingsVectorSelect } from "./Settings Vector - Select.svg";
export { default as shieldVector } from "./Shield Vector.svg";
export { default as shoppingBadVector } from "./Shopping Bag Vector.svg";
export { default as transactionsVector } from "./Transactions Vector.svg";